### ISSUE TITLE
gedit doesn't register enough frames in CI

### ISSUE THREAD

**Issue by Saviq** [MirServer/mir-ci#22]
The numbers are: `ci(xvfb)  native(local)  xvfb(local)`

|                                         | confined-shell  | mir_demo_server  | mir-kiosk       | ubuntu-frame    |
| --                                      | --              | --               | --              | --              |
| test_active_app[\*-asciinema]           | ` 23   27   29` | ` 22    22   24` | `28    35   35` | `20    23   26` |
| test_active_app[\*-mir-kiosk-neverputt] | ` 76  591  705` | `124  1869  989` | `99  2359  938` | `91  1203  805` |
| test_compositor_alone[\*]               | `  9    6    6` | `  2     2    2` | `10    10   10` | ` 2     3    3` |
| test_inactive_app[\*-gedit]             | `  6   46   51` | `  2    40   58` | `10    46   47` | ` 2    22   22` |
| test_inactive_app[\*-mir-kiosk-kodi]    | ` 19  163   89` | ` 17   181   94` | `25   164   94` | `14   154   84` |
| test_inactive_app[\*-qterminal]         | ` 10   13   13` | `  5     7    8` | `12    19   17` | ` 5    10    9` |

So the gedit case looks weirdest.

_Originally posted by @Saviq in https://github.com/MirServer/mir-ci/issues/19#issuecomment-1505056196_

**Comment by wmww** [comment]
Oh, is this doing the thing where gedit takes 30 seconds to come up because the d-bus thingy isn't set?

**Comment by Saviq** [comment]
Fixed by #35
